# IONOS Deploy Now — deployment configuration (schema v1.0)
# https://docs.ionos.space/docs/deployment-configuration/

version: 1.0

deploy:
  bootstrap:
    excludes:
      - .git
      - .github
      - .idea
      - .DS_Store
      - scripts

  recurring:
    excludes:
      - .git
      - .github
      - .idea
      - .DS_Store
      - scripts
